# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
 
# Set name of the theme to load.
ZSH_THEME="theunraveler"

# Red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"
 
# Enable oh my zsh plugins
plugins=(autojump debian tmux svn python pip git git-extras docker docker-compose)
 
# Enable oh my zsh
source $ZSH/oh-my-zsh.sh

# Source bashrc file
source .bashrc

# Powerline
#. ~/.config/powerline/powerline/bindings/zsh/powerline.zsh

# Add autocompletion for ssh with sshrc
compdef sshrc=ssh
