# Set home environment variable
MYHOME=$HOME
if [ -n "$SSHHOME" ]; then
    MYHOME=$SSHHOME/.sshrc.d
fi

# Path to your oh-my-zsh configuration.
ZSH=$MYHOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="fishy"

# Red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"
 
# Enable oh my zsh plugins
plugins=(autojump debian tmux svn python pip git git-extras docker docker-compose)

# Enable oh my zsh
if [ -f $ZSH/oh-my-zsh.sh ]; then
    source $ZSH/oh-my-zsh.sh
fi

# Source bashrc file
source $MYHOME/.bashrc

# Powerline
#. ~/.config/powerline/powerline/bindings/zsh/powerline.zsh

# Add autocompletion for ssh with sshrc
compdef sshrc=ssh
