#!/bin/bash

echo "      _       _         __ _ _"
echo "   __| | ___ | |_      / _(_) | ___  ___"
echo "  / _\` |/ _ \| __|____| |_| | |/ _ \/ __|"
echo " | (_| | (_) | ||_____|  _| | |  __/\__ \\"
echo "  \__,_|\___/ \__|    |_| |_|_|\___||___/"
echo ""

# setup
echo "==> Start Setup"
cd ~/.config/dotfiles/

# Fetch
echo "  > Pulling latest dot-files..."
git pull &> /dev/null

# i3
echo "  > Configure i3..."
rm -rf ~/.config/i3
ln -s ~/.config/dotfiles/i3 ~/.config/i3

# sublime-text-3
echo "  > Configure sublime text..."
rm -rf ~/.config/sublime-text-3/Packages/User
ln -s ~/.config/dotfiles/sublime-text-3 ~/.config/sublime-text-3/Packages/User

# git
echo "  > Configure Git..."
rm -rf ~/.gitconfig
ln -s ~/.config/dotfiles/git/gitconfig ~/.gitconfig
chmod +x ~/.config/dotfiles/git/my-git-meld

# zsh
echo "  > Configure zsh..."
rm -rf ~/.zshrc
ln -s ~/.config/dotfiles/zsh/zshrc ~/.zshrc

# vim
echo "  > Configure Vim..."
rm -rf ~/.vimrc
rm -rf ~/.vim/
ln -s ~/.config/dotfiles/vim/vimrc ~/.vimrc
ln -s ~/.config/dotfiles/vim/vim/ ~/.vim

# Submodules
echo "  > Fetching submodules..."
git submodule init &> /dev/null
git submodule update &> /dev/null

echo "==> Done setup"

