#!/bin/bash

echo "      _       _         __ _ _"
echo "   __| | ___ | |_      / _(_) | ___  ___"
echo "  / _\` |/ _ \| __|____| |_| | |/ _ \/ __|"
echo " | (_| | (_) | ||_____|  _| | |  __/\__ \\"
echo "  \__,_|\___/ \__|    |_| |_|_|\___||___/"
echo ""

DOTPATH=~/.config/dotfiles

# setup
echo "==> Start Setup"
cd $DOTPATH

# Fetch
echo "  > Pulling latest dot-files..."
git pull &> /dev/null

# Submodules
echo "  > Fetching submodules..."
git submodule init &> /dev/null
git submodule update &> /dev/null

# Powerline
echo "  > Configure powerline"
rm -rf ~/.config/powerline
ln -s $DOTPATH/powerline ~/.config/powerline
mkdir -p ~/.fonts/
rm -rf ~/.fonts/PowerlineSymbols.otf
ln -s $DOTPATH/powerline/font/PowerlineSymbols.otf ~/.fonts/PowerlineSymbols.otf
fc-cache -vf ~/.fonts/ &> /dev/null
mkdir -p ~/.config/fontconfig/conf.d/
rm -rf ~/.config/fontconfig/conf.d/10-powerline-symbols.conf
ln -s $DOTPATH/powerline/font/10-powerline-symbols.conf ~/.config/fontconfig/conf.d/10-powerline-symbols.conf

# i3
echo "  > Configure i3..."
rm -rf ~/.config/i3
#ln -s $DOTPATH/i3 ~/.config/i3

# sublime-text-3
echo "  > Configure sublime text..."
rm -rf ~/.config/sublime-text-3/Packages/User
ln -s $DOTPATH/sublime-text-3 ~/.config/sublime-text-3/Packages/User

# git
echo "  > Configure Git..."
rm -rf ~/.gitconfig
ln -s $DOTPATH/git/gitconfig ~/.gitconfig

# zsh
echo "  > Configure zsh..."
rm -rf ~/.oh-my-zsh
wget -q https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - | sh &> /dev/null
rm -rf ~/.zshrc
rm -rf ~/.zshrc.pre-oh-my-zsh
ln -s $DOTPATH/zsh/zshrc ~/.zshrc
ln -s $DOTPATH/zsh/mine.zsh-theme ~/.oh-my-zsh/themes/mine.zsh-theme

# vim
echo "  > Configure Vim..."
rm -rf ~/.vimrc
rm -rf ~/.vim
ln -s $DOTPATH/vim/vimrc ~/.vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim &> /dev/null

# tmux
echo "  > Configure Tmux..."
rm -rf ~/.tmux.conf
ln -s $DOTPATH/tmux/tmux.conf ~/.tmux.conf

# sshrc
echo "  > Configure SSHRC..."
rm -rf ~/.sshrc
rm -rf ~/.sshrc.d
mkdir ~/.sshrc.d
ln -s $DOTPATH/sshrc/sshrc ~/.sshrc
ln -s $DOTPATH/vim/vimrc ~/.sshrc.d/.vimrc
#ln -s ~/.vim ~/.sshrc.d/.vim
ln -s $DOTPATH/git/gitconfig ~/.sshrc.d/.gitconfig

# bin files
echo "  > Configure user bin softs..."
rm -rf ~/.bin
ln -s $DOTPATH/bin/ ~/.bin

echo "==> Done setup"

