" VIM Configuration 
" Annule la compatibilite avec l’ancetre Vi : totalement indispensable
set nocompatible

" Use powerline
set rtp+=~/.config/powerline/powerline/bindings/vim/

" Always show statusline
set laststatus=2

" Use 256 colours
set t_Co=256

" Activation de pathogen
runtime! autoload/pathogen.vim
if exists("*pathogen#infect")
    call pathogen#infect()
endif
"execute pathogen#infect()

" -- Affichage
set title               " Met a jour le titre de votre fenetre ou de votre terminal
set number              " Affiche le numero des lignes
set ruler               " Affiche la position actuelle du curseur
set wrap                " Affiche les lignes trop longues sur plusieurs lignes
set scrolloff=3         " Affiche un minimum de 3 lignes autour du curseur (pour le scroll)

" -- Recherche
set ignorecase          " Ignore la casse lors d’une recherche
set smartcase           " Si une recherche contient une majuscule, re-active la sensibilite a la casse
set incsearch           " Surligne les resultats de recherche pendant la saisie
set hlsearch            " Surligne les resultats de recherche

" -- Beep
set visualbell          " Empeche Vim de beeper
set noerrorbells        " Empeche Vim de beeper

" Active le comportement ’habituel’ de la touche retour en arriere
set backspace=indent,eol,start

" Cache les fichiers lors de l’ouverture d’autres fichiers
set hidden

" Active la coloration syntaxique
syntax enable

" Active les comportements specifiques aux types de fichiers comme la syntaxe et l’indentation
filetype on
filetype plugin on
filetype indent on

" Police
set guifont=Droid\ Sans\ Mono\ 10
set antialias

" Desactiver les touches directionnelles
"map <up> <nop>
"map <down> <nop>
"map <left> <nop>
"map <right> <nop>
"imap <up> <nop>
"imap <down> <nop>
"imap <left> <nop>
"imap <right> <nop>

" Remplacer echap. Les ; sont rarement utilises l’un a la suite de l’autre
:imap <special> ,, <Esc>

" Changement de la touche leader
let mapleader = ","

" Regles python
set tabstop=4
set shiftwidth=4
set expandtab

" BÉPO CONFIG

" Move next word
noremap é w
" Move next WORD
noremap É W
 
" Move carret left
noremap c h
" Move carret right
noremap r l
" Move carret down
noremap t j
" Move carret up
noremap s k
" Move carret at the top of the screen
noremap C H
" Move carret at the bottom of the screen
noremap R L
" Join lines
noremap T J
" Run a program to lookup the keyword under the cursor
noremap S K

" Move to character before following typed character (unTill)
noremap j t
" Move to character before following typed character (unTill) backward
noremap J T
" Replace character under cursor
noremap l r
" Enter Replace mode
noremap L R
" Change text according to next motion command
noremap h c
" Change until end of the line
noremap H C
" Subtitute text according to next command
noremap k s
" Subtitute the whole line
noremap K S