# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
 
# Set name of the theme to load.
ZSH_THEME="theunraveler"

# red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"
 
# enable oh my zsh plugins
plugins=(autojump debian)
 
source $ZSH/oh-my-zsh.sh
 
# Customize to your needs...
 
# Path
export PATH=$PATH:~/.bin/
export PATH=$PATH:~/.gem/ruby/2.1.0/bin/
 
# Alias
alias zshr="source ~/.zshrc"
alias raspi="ssh pi@brvt.no-ip.org"
alias ...="../../"
alias Lab="~/Lab/"
alias lab="~/Lab/"
alias dock="docker"
alias dockc="docker-compose"
alias ans="ansible"
alias ansp="ansible-playbook"
alias ssh="sshrc"
alias venv="source venv/bin/activate"
alias extip="wget http://ipinfo.io/ip -qO -"

alias py="python"
alias ipy="ipython"
alias py3="python3"
alias ipy3="ipython3"
alias dj="python manage.py"

# Launch ls after cd command
function chpwd() {
    emulate -L zsh
    ll
}

# Always work in a tmux session if tmux is installed
#if which tmux 2>&1 >/dev/null; then
#    if [ $TERM != "screen-256color" ] && [  $TERM != "screen" ]; then
#        tmux attach -t hack || tmux new -s hack; exit
#    fi
#fi

# Powerline
#. ~/.config/powerline/powerline/bindings/zsh/powerline.zsh
### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
